# Generated by Django 4.0.3 on 2022-04-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contract_type',
            new_name='contract',
        ),
    ]
